PierresBakery/Models/Flavor.cs
using System.Collections.Generic;

namespace PierresBakery.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.JoinEntries = new HashSet<TreatFlavor>();
    }

    public int FlavorId { get; set; }
    public string FlavorName { get; set; }

    public ICollection<TreatFlavor> JoinEntries { get; }
  }
}  

PierresBakery/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using PierresBakery.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;


namespace PierresBakery.Controllers
{
  
  public class FlavorsController : Controller
  {
    private readonly PierresBakeryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierresBakeryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor, int TreatId)
    {
      _db.Flavors.Add(flavor);
      if (TreatId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
          .Include(flavor => flavor.JoinEntries)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }
    
    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.Entry(flavor).State=EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }
    
    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if(TreatId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId});
      }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  
    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

PierresBakery/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor

<h2>Add a treat</h2>

<h4>Add a Treat for this flavor: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select a treat")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierresBakery/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor  

<h4>Add a new Flavor</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.FlavorName)
    @Html.TextBoxFor(model => model.FlavorName)

    @Html.Label("Select Treat")
    @Html.DropDownList("TreatId") 

    <input type="submit" value="Add new flavor" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all flavors", "Index")</p>

PierresBakery/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor

<h2>Are you sure you want to delete this flavor?</h2>

@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

PierresBakery/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor

<h2>Flavors Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)</h3>

@if(Model.JoinEntries.Count == 0)
{
  <p>This Flavor does not belong to any Treats</p>
}
else
{
  <h4>Treats the Flavors belongs to:</h4>
}

  <ul>
  @foreach(var join in Model.JoinEntries)
  {
    <li>@join.Treat.TreatName</li>
    @using (Html.BeginForm("DeleteTreat", "Flavors"))
    {
      @Html.Hidden("joinId", @join.TreatFlavorId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
  
<p>@Html.ActionLink("Add a treat", "AddTreat", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>

PierresBakery/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor

<h2>Edit</h2>

<h4>Edit this Flavors info: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.FlavorName)
    @Html.EditorFor(model => model.FlavorName)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierresBakery/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresBakery.Models;
@model List<PierresBakery.Models.Flavor>;

<h1>Flavors</h1>

@if (@Model.Count == 0)
{
  <h3>No Flavors have been added yet!</h3>
} 

@foreach (Flavor flavor in Model)
{
  <li>@Html.ActionLink($"{flavor.FlavorName}", "Details", new { id = flavor.FlavorId })</li>
}

<p>@Html.ActionLink("Add new flavor", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>